spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://sql12.freesqldatabase.com:3306/sql12823164?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sql12823164}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gHp5VvE6Ae}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}